"""create remaining tables

Revision ID: bcfff7642208
Revises: cb96b755432a
Create Date: 2026-03-19 14:30:08.673347

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'bcfff7642208'
down_revision: Union[str, None] = 'cb96b755432a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('track', sa.String(length=200), nullable=False),
    sa.Column('car', sa.String(length=200), nullable=False),
    sa.Column('simulator', sa.String(length=10), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('best_lap', sa.Float(), nullable=False),
    sa.Column('avg_lap', sa.Float(), nullable=False),
    sa.Column('weak_sector', sa.String(length=5), nullable=True),
    sa.Column('trend', sa.Float(), nullable=False),
    sa.Column('corner_profiles', sa.JSON(), nullable=True),
    sa.Column('common_setup', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_profiles_user_id'), 'knowledge_profiles', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('active', 'canceled', 'past_due', 'trialing', name='substatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('simulator', sa.Enum('ac', 'r3e', name='simulator'), nullable=False),
    sa.Column('track', sa.String(length=200), nullable=False),
    sa.Column('car', sa.String(length=200), nullable=False),
    sa.Column('session_type', sa.Enum('practice', 'qualify', 'race', name='sessiontype'), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_time', sa.Float(), nullable=False),
    sa.Column('s1', sa.Float(), nullable=False),
    sa.Column('s2', sa.Float(), nullable=False),
    sa.Column('s3', sa.Float(), nullable=False),
    sa.Column('tyre_compound', sa.String(length=100), nullable=False),
    sa.Column('track_temp', sa.Float(), nullable=False),
    sa.Column('ambient_temp', sa.Float(), nullable=False),
    sa.Column('track_length', sa.Float(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('upload', 'drive', name='sourcetype'), nullable=False),
    sa.Column('csv_path', sa.String(length=500), nullable=False),
    sa.Column('session_date', sa.String(length=30), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('drive_pdf_link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_sessions_user_id'), 'telemetry_sessions', ['user_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='analysisstatus'), nullable=False),
    sa.Column('pre_analysis', sa.JSON(), nullable=True),
    sa.Column('ai_result', sa.JSON(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['telemetry_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_session_id'), 'analyses', ['session_id'], unique=True)
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    op.create_table('pilot_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['telemetry_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pilot_notes_session_id'), 'pilot_notes', ['session_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('tested', sa.Boolean(), nullable=False),
    sa.Column('delta_improvement', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['knowledge_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_analysis_id'), 'recommendations', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_analysis_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_pilot_notes_session_id'), table_name='pilot_notes')
    op.drop_table('pilot_notes')
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_session_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_telemetry_sessions_user_id'), table_name='telemetry_sessions')
    op.drop_table('telemetry_sessions')
    op.drop_table('teams')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_knowledge_profiles_user_id'), table_name='knowledge_profiles')
    op.drop_table('knowledge_profiles')
    # ### end Alembic commands ###
